

import Head from 'next/head'
import withAuth from '@/routes/ProtectedRoute'

function Home() {
    return (
        <>
            <Head>
                <title>HedWig</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main></main>
        </>
    )
}

export default withAuth(Home)
