import CustomCard from '@/components/customCard'
import postsData from '@/components/customCard/data'
import Head from 'next/head'
import Link from 'next/link'
export default function Home() {
    return (
        <>
            <Head>
                <title>HedWig</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {/* mobile size default as 400px */}
                <div style={{ width: '400px' }}>
                    {postsData.map(post => (
                        <CustomCard key={`${post.createdAt}`} type="POST" data={post} />
                    ))}
                </div>
            </main>
        </>
    )
}
